import Link from "next/link";
import { ArrowRight, BarChart3, Brackets, Gauge, Route, ShieldCheck, Trophy } from "lucide-react";

const features = [
  [Brackets, "48-team format", "Model all 12 groups, the best third-place table, and FIFA's official Round-of-32 structure."],
  [Gauge, "Explainable simulation", "Poisson scorelines and seeded Monte Carlo runs keep every probability reproducible."],
  [Route, "Plain-English paths", "Understand who controls their fate, who needs help, and which knockout route is waiting."],
];

export default function Home() {
  return <><section className="shell grid min-h-[72vh] items-center gap-10 py-16 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">The expanded World Cup, made understandable</p><h1 className="font-display mt-4 max-w-4xl text-6xl font-bold leading-[.92] md:text-8xl">Predict the <span className="text-cyan-300">2026 World Cup.</span></h1><p className="muted mt-6 max-w-2xl text-lg leading-8">Edit scores, simulate paths, and see who advances through all 12 groups and the new 32-team knockout stage.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/simulator" className="button button-primary">Start simulator <ArrowRight size={17}/></Link><Link href="/simulations" className="button button-secondary"><BarChart3 size={17}/> Run Monte Carlo</Link></div><div className="mt-10 flex flex-wrap gap-5 text-sm text-slate-400"><span className="flex items-center gap-2"><ShieldCheck size={16} color="var(--success)"/> Official bracket mapping</span><span className="flex items-center gap-2"><Trophy size={16} color="var(--amber)"/> 48 teams · 104 matches</span></div></div><div className="card relative overflow-hidden p-5 md:p-8"><div className="absolute right-[-4rem] top-[-4rem] h-48 w-48 rounded-full bg-blue-500/20 blur-3xl"/><p className="eyebrow">Live model board</p><h2 className="font-display mt-2 text-3xl font-bold">One prediction changes every path.</h2><div className="mt-7 space-y-3">{[["Group winners", "12"], ["Automatic qualifiers", "24"], ["Best third-place teams", "8"], ["Knockout field", "32"]].map(([label,value],index)=><div key={label} className="flex items-center justify-between rounded-xl border border-[var(--border)] bg-[#071523] p-4"><span className="text-slate-300">{label}</span><span className={`font-data text-2xl font-bold ${index===3?'text-amber-300':'text-cyan-300'}`}>{value}</span></div>)}</div></div></section><section className="shell pb-16"><div className="grid gap-4 md:grid-cols-3">{features.map(([Icon,title,body])=><article key={String(title)} className="card p-6"><Icon color="var(--cyan)"/><h2 className="font-display mt-5 text-2xl font-bold">{String(title)}</h2><p className="muted mt-2 leading-7">{String(body)}</p></article>)}</div></section></>;
}

