"use client";

import { useMemo, useState } from "react";
import { BarChart3, Play } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { apiFetch } from "@/lib/api";
import type { Probability } from "@/lib/types";
import { ProbabilityBar } from "./ProbabilityBar";

export function SimulationControls({ runs, setRuns, onRun, busy }: { runs: number; setRuns: (runs: number) => void; onRun: () => void; busy: boolean }) { return <div className="flex flex-wrap items-center gap-3"><label className="text-sm text-slate-300">Runs <select className="ml-2 rounded-lg border border-[var(--border)] bg-slate-950 px-3 py-2" value={runs} onChange={(event) => setRuns(Number(event.target.value))}><option>100</option><option>500</option><option>1000</option><option>5000</option></select></label><button className="button button-primary" disabled={busy} onClick={onRun}><Play size={16}/>{busy ? "Running…" : "Run model"}</button></div>; }

export function SimulationsClient() {
  const [runs, setRuns] = useState(500); const [group, setGroup] = useState("ALL"); const [rows, setRows] = useState<Probability[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const filtered = useMemo(() => rows.filter((row) => group === "ALL" || row.group === group), [rows, group]);
  async function run() { setBusy(true); setError(""); try { const result = await apiFetch<{ teams: Probability[] }>(`/simulations/monte-carlo?runs=${runs}&seed=2026`); setRows(result.teams); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  return <div className="shell py-10"><p className="eyebrow">Monte Carlo lab</p><h1 className="font-display mt-2 text-5xl font-bold">Tournament probabilities</h1><p className="muted mt-3 max-w-2xl">Run thousands of seeded tournaments through the same Poisson model that powers match predictions.</p><div className="card mt-8 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><SimulationControls runs={runs} setRuns={setRuns} onRun={run} busy={busy}/><select aria-label="Filter by group" className="rounded-lg border border-[var(--border)] bg-slate-950 px-3 py-2" value={group} onChange={(event) => setGroup(event.target.value)}><option value="ALL">All groups</option>{"ABCDEFGHIJKL".split("").map((id) => <option key={id}>{id}</option>)}</select></div>{error && <p className="mt-4 text-rose-300">{error}</p>}</div>
    {!rows.length ? <div className="card mt-6 p-12 text-center"><BarChart3 className="mx-auto text-slate-500"/><h2 className="font-display mt-3 text-2xl font-bold">Run the model to populate the board</h2></div> : <><div className="card mt-6 h-[460px] min-w-0 p-4"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={320}><BarChart data={filtered.slice(0, 16)} layout="vertical" margin={{ left: 20, right: 24 }}><CartesianGrid stroke="#243b58" horizontal={false}/><XAxis type="number" domain={[0, 1]} tickFormatter={(value) => `${Math.round(value * 100)}%`} stroke="#94a3b8"/><YAxis type="category" dataKey="team_name" width={110} stroke="#cbd5e1"/><Tooltip formatter={(value) => `${(Number(value) * 100).toFixed(1)}%`} contentStyle={{ background: "#0c1a2b", border: "1px solid #243b58" }}/><Bar dataKey="probability_champion" fill="#22d3ee" radius={[0, 6, 6, 0]}/></BarChart></ResponsiveContainer></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.slice(0, 12).map((row) => <article key={row.team_id} className="card p-5"><div className="mb-4 flex justify-between"><h3 className="font-display text-xl font-bold">{row.team_name}</h3><span className="font-data text-xs text-slate-500">Group {row.group}</span></div><div className="space-y-3"><ProbabilityBar label="Qualify" value={row.probability_qualify}/><ProbabilityBar label="Reach semifinal" value={row.probability_semifinal}/><ProbabilityBar label="Champion" value={row.probability_champion}/></div></article>)}</div></>}
  </div>;
}
